server:
  port: 5100
spring:
  application:
    name: cajr-provider-basic-data
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
