server:
  port: 7200

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cajr?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123zxc
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123zxc
    timeout: 1000ms
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#  cache:
#    type: redis
#    redis:
#      time-to-live: 200000ms
#      cache-null-values: false
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
