server:
  port: 8200
spring:
  application:
    name: cajr-security-auth-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    org.springframework: DEBUG