server:
  port: 8300
spring:
  application:
    name: cajr-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
     nacos:
       discovery:
         server-addr: 127.0.0.1:8848
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000